### PR TITLE
Jed/flickrinject

### PR DESCRIPTION
**Pull request by Jedeu**
We can now finally has JS injection onto Flickr websites + general websites with img tags! Pressing "photon" button now collects img url and the native dimensions of the photo.

Please test and provide feedback kthx

### CODE REVIEW

**Comment by LaurelOlson** [comment]
Typo in manifest.json prevents extension from loading - line 61 should be ./embeds/500px.js I think??

Also as a note, you need to npm install bower (if you don't already have bower) and then bower install jquery to get the jquery file to exist.

After doing that, the extension seems to work fine for flickr on my end!

**Comment by Jedeu** [comment]
Hmm that's weird. I just took a look at the commit on github. Isn't that what it is already in this commit? Anyway someone can haz pull if Billiam also thinks it's good!

**Comment by LaurelOlson** [comment]
Yea idk, I was having some weird issues with getting a pull to work so it is entirely possible that I just did not get that commit. Just looked through the actual code and everything looks good to me! Found a few nitpicky things you can look at if you want.

photon-flickr.js 
- if you run through jshint (sublime package), a few semi-colons missing and a few functions/variables are defined but never used (getStyleOfImg and it's variables, line 25; addPhotoButton, line 129).
- line 45: consider renaming checkIfUnderstoreIsPath to underscoreIsPath as it returns a boolean? This may improve readability when the function is called (i.e. if (underScoreIsPath) { .. }. I think you can also just say return underScoreFragment.length > 1, which should return true if true, false if false (rather than the if/else statement).

**Comment by Jedeu** [comment]
Photon-500px.js is now added. Try using it again!

**Comment by Jedeu** [comment]
@LaurelOlson and @billiamliu now confirmed that the icon interface will work with all image tags on the interwebz, 500px and Flickr. Now on to IXD! Someone please approve and merge this request.

**Pull request merged**
